[project]
name = "llm-mech-interp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.12.0",
    "certifi>=2025.4.26",
    "datasets>=4.4.2",
    "modal>=1.3.0.post1",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]
